title: Standaard pagina
options:
  changeStatus: true
tabs:
  content:
    sections: # here come the sections
      fields: # a fields section
        type: fields
        fields:
          line1:
            type: line

      pages: sections/builder

        # section1: sections/example

  # files: tabs/files
  bestanden: tabs/files
  seo: seo/page
