title: Site
#preset: pages
#unlisted: true
options:
  changeTitle: false
tabs: 
  main:
    label: Pagina's
    icon: page
    sections:
      fields:
        type: fields
        fields:
          nav1:
            label: Navigatie
            type: multiselect
            translate: false
            options:
              type: query
              query: site.children.listed
              text: "{{ item.title}}"
              value: "{{ item.id }}"
          
          line1:
            type: line
          
      hidden1:
        type: pages
        headline: Onzichtbare pagina's
        image: false
        templates:
          - legal
      
      pages1:
        type: pages
        headline: Pagina's
        image: false
        templates:
          - home
          - blogs
          - default
          - contact

      fields2:
        type: fields
        fields:
          line2:
            type: line
          
          contact1:
            label: Contact informatie
            type: object
            fields:
              email1:
                label: Email
                type: email
              tel1:
                label: Telefoon
                type: text
              straat1:
                label: Straat
                type: text
              zip1:
                label: Postcode
                type: text
                width: 1/2
              city1:
                label: Gemeente
                type: text
                width: 1/2
              country1:
                label: Land
                type: text
              btw1:
                label: BTW Nummer
                type: text
        
          
          socials1:
            label: Social Media
            type: structure
            entry: >
              {{socialtype1}}
            fields:
              socialtype1:
                label: Social Media Platform
                type: text
              socialurl1:
                label: Social Media link
                type: url


  variables:
    label: Website instellingen
    icon: cog
    fields:

      timestamp:
        label: Timestamp
        type: number

      scripts1:
        label: Scripts
        type: textarea
        buttons: false
        translate: false
  seo: seo/site
