title: Site
#preset: pages
#unlisted: true
options:
  changeTitle: false
tabs: 
  main:
    label: Pagina's
    icon: page
    sections:
      fields:
        type: fields
        fields:
          nav1:
            label: Navigatie
            type: multiselect
            translate: false
            options:
              type: query
              query: site.children.listed
              text: "{{ item.title}}"
              value: "{{ item.id }}"
          
          line1:
            type: line
          
      hidden1:
        type: pages
        headline: Onzichtbare pagina's
        image: false
        templates:
          - privacy
      
      pages1:
        type: pages
        headline: Pagina's
        image: false
        templates:
          - home
          - default
          - contact

      fields2:
        type: fields
        fields:
          line2:
            type: line
          
          contact1:
            label: Alg. informatie
            type: textarea
            width: 1/3
          
          info1:
            label: Info
            type: structure
            fields:
              icon1:
                label: Icon
                type: select
                options:
                  - mail
                  - phone
                  - location
              text1:
                label: Text
                type: textarea
          
          newsletter1:
            label: Contact
            type: textarea
          
          socials1:
            label: Social Media
            type: structure
            entry: >
              {{socialtype1}}
            fields:
              socialtype1:
                label: Social Media Platform
                type: radio
                options:
                  facebook: Facebook
                  instagram: Instagram
                  linkedin: LinkedIn
              socialurl1:
                label: Social Media link
                type: url


  variables:
    label: Website instellingen
    icon: cog
    fields:

      timestamp:
        label: Timestamp
        type: number

      scripts1:
        label: Scripts
        type: textarea
        buttons: false
        translate: false
  seo: seo/site
